### PR TITLE
Create Copy videos from SD to NAS by ftp

### PR DESCRIPTION
**Pull request by garvarma**
Here there is a script thtat videos from SD card, can make a copy to a NAS

### CODE REVIEW

**Comment by fritz-smh** [comment]
Can you give me a few lines to add in the doc to explain how to use it ?
Then, I will merge this PR

And thanks :)

**Comment by garvarma** [comment]
Well, for security or backup this script makes a copy of videos/records from the sd (/home/hd1/record) to a device (nas or pc) using ftpd protocol from camera to a ftp server (nas)

Thanks

Enviado desde mi iPhone

**Comment by garvarma** [comment]
Hi,
Here you have the explanation:
* ftp_dir value, just put there the path where you want to copy videos.
* ftp_host value, indicate the IP of the NAS
* ftp_port value, indicate the port of the FTP server (like 21)
* ftp_login value, indicate the user or login to connect to the ftp folder in the nas server.
* ftp_pass value, indicate the password of the user before for permision to save in the folder.

Just is necessary these 5 values to complete. After this, only save script in the init.sh.

**Comment by trust199** [comment]
there is a new version: [http://4pda.ru/forum/index.php?showtopic=638230&st=2780#entry44208114](url)

**Comment by garvarma** [comment]
Hi, 
This is no a new version, mine i took from this website or link.

Just i share it, because nobody added

Thanks

**Comment by fritz-smh** [comment]
I don't forget this PR, just very busy these days. Will merge in a few days

**Comment by ajinkyajin** [comment]
Please mention the steps to enable it on to cam.

**Comment by garvarma** [comment]
Hi ajinkyajin,

First of all you this script send records to a ftp server.
1. Create a user/password in your ftp server.
2. In the script, there is a variable called "dir" that you need to complete with route (pwd). Also need to add the user and the password in variables in the script.
3. (I'm not sure with this step) i'm not in front of cam and don't want to mistake, i Will tell you in other moment

Sorry

**Comment by fritz-smh** [comment]
Merged, moved in sd/test/scripts with a bit of doc.

Thanks again !

**Review by albarzoida — APPROVED** [review]
1

**Pull request merged**
