### PR TITLE
Create Script detele file or videos after few days

### PR DESCRIPTION
**Pull request by garvarma**
Delete records from SD or device after X days, and generate a log file.

### CODE REVIEW

**Comment by fritz-smh** [comment]
Hi,

Are you sure a final / is not missing in the dir variable ?
The log is generated in the record dir, is this the goal ?

Thanks for the PR, I wait your answer before merging.

++
Fritz

**Comment by garvarma** [comment]
Hello, 
Well i did it into my NAS and worked well, dir variable is defined at the beginning.

I must check it in camera, but as i told you, in  my nas worked well

Yes, log is created in the dir variable with the date that is execute script.

From my side, i have few questions about main or default web in http server in xiaomi

Can you help me?

Enviado desde mi iPhone

**Comment by garvarma** [comment]
Hello,
Yesterday i didn't checked code, and reply sorry.
Now i can see that you are right, is missing / in the dir variable. And as i told you, log is generated in the record dir.

thanks

**Comment by fritz-smh** [comment]
OK, do you plan to fix this PR or du you expect me to do the fix after
merging (just to know).

About the question on the web server, please create a ticket with your
questions, it will be easier for me to follow :)

**Comment by nono56** [comment]
Hello!
Where did you put this file please?
How do you execute this file? Cron?
Thanks

**Comment by garvarma** [comment]
Hi,
You can put it where you want, just you must put in variable dir= the route where are videos and folders.
You can execute with ./namefile.sh, but if you want do it automatic, then yes, execute qith cron

**Comment by nono56** [comment]
Thanks!

**Comment by fritz-smh** [comment]
I don't forget this PR, just very busy these days. Will merge in a few days

**Comment by k4r4su** [comment]
Hi,

I have execute this script directly on the XiaoYi Camera and : 
- the du -bsh command have a pb :  -b isnt recognize.
- the missing "/" in the dir variable.

Except this, it works well.

Thank you :)

**Comment by garvarma** [comment]
Hi,
I didn't checked already script on camera because some friends asked to me to check camera and now i don't have it. But i checked on my nas and worked.

Once i will have it i will check

Thanks

Enviado desde mi iPhone

**Comment by fritz-smh** [comment]
Hi,

Were you able to check ?

Thanks,
Fritz

**Comment by coomsie** [comment]
Gidday,

for this to work for me .... below are the changes

 dir="/home/hd1/record/"

i.e. add '/' at end

du -sh ${dir} > ${dir}Delete_$dt.log
du -sh ${dir} >> ${dir}Delete_$dt.log

remove the -b

**Comment by fritz-smh** [comment]
Applied in https://github.com/fritz-smh/yi-hack/commit/a01f61f4329eff97abc20f13d765bc885b1235ab

**Comment by fritz-smh** [comment]
small update : https://github.com/fritz-smh/yi-hack/commit/27e3fa9dfcd2a88e7e2501cb17684614957e07cd

**Pull request closed without merging**
