### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by death2all110**
Update git clone line to point to my repo

### CODE REVIEW

**Comment by walmer-bolfet** [comment]
Greeting from Alabama,

I updated to this lastest build and now my camera doesn't save files.  It will stream ok - both on the app and on RTSP channels.  The app will also detect motion and send an alert with the 6 video sec clip.

This found in the /home/hd1/test/log_motion.txt file may be related. 

Checking for motion at Thu Mar 30 10:56:11 CDT 2017...
Motion file: 
/home/hd1/test/check_motion.sh: line 25: can't create /home/hd1/test/http/motion: Read-only file system

What to do?

RB Paul

**Comment by death2all110** [comment]
@rbpaul 

Yes, I noticed this myself. I've already fixed the issue, but I am at work right now. I will push my changes this evening. The fix will be in my fork: https://github.com/death2all110/yi-hack

**Comment by death2all110** [comment]
Also, This pull request was created last night by mistake. That is why it is closed.

**Comment by walmer-bolfet** [comment]
Greetings death2all110 

I did get the build from your fork at: https://github.com/death2all110/yi-hack  
I will look again there in the morning. Thanks.

Some additional observations:

Poking around, I came across these entries at the end of dmesg:
     FAT-fs (mmcblk0p1): error, fat_free_clusters: deleting FAT entry beyond EOF
     FAT-fs (mmcblk0p1): Filesystem has been set read-only

So I reformatted my SD card and started again. Files are being saved now (and no Filesystem set to read-only in dmesg).   It looks like the same files are saved in two places, it that normal?
    One save at:  /home/hd1/test/http/record/
    The same at: /home/hd1/record/ 

Nevertheless, when I go to the web interface, nothing shows at the "Records Files" link.  When I “Click here to access the record files.”  It shows only the “last_motion_check” link.

Also, can you speak to some issues I have with the app? 
     1) When video is recorded, the app time-line shows the video to have been recorded an hour into the future than the actual time. 
     2) I don’t seem to be able to use the app to view recorded video the way I was able to before I applied the hack.  

Thank you again
RB Paul

**Comment by death2all110** [comment]
There is a bind mount that mounts /home/hd1/test/http/record to /home/hd1/record. Not sure why files are not showing up for you. I'll look into it this evening.

As for the timeline issue, its an app issue and I'm trying to find a fix, but I've yet to find one. Its not hack related, because it even happens on stock.

Can you explain Question 2 further?

**Comment by walmer-bolfet** [comment]
I just received another camera and out of the box it behaves different with the app than the hacked camera.  

The new camera has firmware version 1.8.6.1B_201604071154.  The hacked camera has 1.8.7.0A_201502081101.  Perhaps what I am seeing is a firmware difference.  

1. The new camera shows the recorded video (i.e., Playback History) on the timeline at the correct time, not 1 hour into the future.

2. The new camera allows me to move up and down the timeline to where there are shaded areas indicating Playback History.  When I stop moving on the timeline with the indicator bar in the shaded playback history area, then the app plays the recorded video.  I can’t do this on the hacked camera.  When I stop moving on the timeline with the hacked camera, then the indicator bar automatically bounces back to the current time, and displays the live feed.

Does this help?

Thanks

**Comment by death2all110** [comment]
Have you verified the timezone in yi-hack.cfg is correct?

As for 2. My stock cameras at home don't even work like this sadly. I've never been able to get the timeline to work properly. So I'm honestly not sure.

**Comment by walmer-bolfet** [comment]
I have upgraded to the latest firmware on the new camera that is not hacked.  It continues to work as before, so I don't believe these are firmware issues. The playback feature is very handy. If it could be fixed that would be great. 

The time stamp issue occurs only on the app timeline of the hacked camera. I don't think it is a time zone issue. The correct time zone appears in the app, and the saved files are created with the correct time stamp. When I telnet into the hacked camera, I can see it is set to the right time. 

Thanks, and good luck.

**Pull request closed without merging**
