### PR TITLE
Update yi-hack.cfg

### PR DESCRIPTION
**Pull request by sourcejon**
Added examples of time zones that respect daylight savings

Set default time zone to GMT0BST,M3.5.0/1,M10.5.0

### CODE REVIEW

**Comment by coomsie** [comment]
Gidday,

Great thanks for this .... works a treat in NZ 👍

**Comment by BjoernT** [comment]
👍

**Comment by kot7k** [comment]
Good tip.

**Comment by fritz-smh** [comment]
Thanks !

Included with PR #42

**Pull request closed without merging**
